// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvwkuqnotnilsbcswfqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2d2t1cW5vdG5pbHNiY3N3ZnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMjY4NjMsImV4cCI6MjA1NzcwMjg2M30.1iiE4PAwM1pf-xxKENPHjpQS48V-OPKVnJCBncfNQZM";

// Helper to check if we're in a browser environment
const isBrowser = typeof window !== 'undefined';

// Custom storage implementation with safety checks
const customStorage = {
  getItem: (key: string): string | null => {
    try {
      if (isBrowser) {
        return localStorage.getItem(key);
      }
      return null;
    } catch (error) {
      console.error('Error accessing localStorage:', error);
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      if (isBrowser) {
        localStorage.setItem(key, value);
      }
    } catch (error) {
      console.error('Error writing to localStorage:', error);
    }
  },
  removeItem: (key: string): void => {
    try {
      if (isBrowser) {
        localStorage.removeItem(key);
      }
    } catch (error) {
      console.error('Error removing from localStorage:', error);
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,               // Enable session persistence
    storageKey: 'therapist-app-auth',   // Unique storage key for the app
    autoRefreshToken: true,             // Automatically refresh token
    detectSessionInUrl: true,           // Detect OAuth session in URL
    storage: customStorage,
  },
});

// Function to clear auth state - useful for debugging
export const clearAuthState = () => {
  try {
    if (isBrowser) {
      localStorage.removeItem('therapist-app-auth');
      console.log('Auth state cleared');
    }
  } catch (error) {
    console.error('Error clearing auth state:', error);
  }
};
